# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sentiment-app
  template:
    metadata:
      labels:
        app: sentiment-app
    spec:
      initContainers:
      - name: download-model
        image: "{{ .Values.initContainers.repository }}:{{ .Values.initContainers.tag }}"
        args:
          - cp
          - sentiment_model.pkl
          - tfidf_vectorizer.pkl
          - /models
        volumeMounts:
        - name: models
          mountPath: /models
      containers:
      - name: sentiment
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: MODEL_PATH
          value: "{{ .Values.env.MODEL_PATH }}"
        - name: VECTORIZER_PATH
          value: "{{ .Values.env.VECTORIZER_PATH }}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: models
          mountPath: /models
      volumes:
      - name: models
        emptyDir: {}