name: Serve pipeline

on:
  push:
    tags:
      - 's*'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker Image for tests
      run: |
          cd serve
          docker build -f Dockerfile_test -t fastapi-tests .

    - name: Run Tests
      run: docker run --rm fastapi-tests

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: "{{defaultContext}}:serve"
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-githubaction-serve:${{ github.ref_name }}
    