name: Training pipeline

on:
  push:
    tags:
      - 'model-*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: train the model
      run: |
        cd data
        docker build . --file Dockerfile --tag ghcr.io/${{github.repository}}/model:$TAG
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push the Docker image
      run: docker push ghcr.io/${{github.repository}}/model:$TAG